# Generated by Django 2.2.1 on 2020-10-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_car_goods_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='goods_total',
        ),
    ]
