# Generated by Django 2.2.1 on 2020-10-15 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_remove_car_goods_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer')),
            ],
        ),
    ]
