# Generated by Django 2.2.1 on 2020-10-16 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_buyeraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32)),
                ('order_date', models.DateField()),
                ('order_address', models.CharField(max_length=128)),
                ('order_total_num', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('goods_num', models.IntegerField()),
                ('goods_total_price', models.CharField(max_length=32)),
                ('goods_img', models.CharField(max_length=32)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.Order')),
            ],
        ),
    ]
