# Generated by Django 2.2.1 on 2020-10-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total_price',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
