# Generated by Django 2.2.1 on 2020-10-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_order_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32)),
                ('check_word', models.CharField(max_length=32)),
                ('date', models.DateField()),
            ],
        ),
    ]
