# Generated by Django 2.2.1 on 2020-10-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_auto_20201019_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkemail',
            name='date',
            field=models.CharField(max_length=32),
        ),
    ]
