# Generated by Django 2.2.1 on 2020-10-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_auto_20201019_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkemail',
            name='date',
            field=models.DateTimeField(max_length=32),
        ),
    ]
