# Generated by Django 2.2.1 on 2020-10-14 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_type',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Seller'),
        ),
    ]
